services:
    show-saver:
        image: show-saver
        container_name: show-saver
        build: .
        ports:
            - 5000:5000
            - 5678:5678
        env_file:
            - ./dev.env
        environment:
            - FLASK_DEBUG=true
        volumes:
            - ./.local/config:/config
            - ./.local/tvshows:/tvshows
            - ./.local/tmp:/tmp